# Generated by Django 4.1.5 on 2023-01-07 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_support_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
