# Generated by Django 4.1.5 on 2023-01-07 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_support_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='activated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarantee',
            name='serial',
            field=models.CharField(default='-', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
