# Generated by Django 4.1.5 on 2023-02-01 08:45

import django.core.validators
from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customer_is_complete_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='notification', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='store/news', validators=[store.validators.validate_file_size])),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
