# Generated by Django 4.1.5 on 2023-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
