# Generated by Django 4.1.7 on 2023-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_order_payment_status_alter_news_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supertag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supertag',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
