# Generated by Django 4.1.7 on 2023-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_group_delete_supertag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
