# Generated by Django 3.2.12 on 2023-03-15 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_support_name_support_user_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
