# Generated by Django 3.2.12 on 2023-04-19 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_order_laststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
