# Generated by Django 3.2.12 on 2023-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_support_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Answered'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
