# Generated by Django 3.2.12 on 2023-06-07 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_support_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('KW1450', 'KW1450'), ('HP1450', 'HP1450'), ('KW2900', 'KW2900'), ('HP2900', 'HP2900')], default='KW1450', max_length=6)),
                ('power', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='store.product')),
            ],
        ),
    ]
