# Generated by Django 3.2.12 on 2023-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_productpowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
