# Generated by Django 4.1.7 on 2023-03-07 05:38

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', validators=[store.validators.validate_file_size])),
            ],
        ),
    ]
